# Generated by Django 3.1.1 on 2020-09-19 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_signup_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='adminPortal',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
