# Generated by Django 3.1.1 on 2020-09-19 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_adminportal'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminportal',
            name='email',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='adminportal',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='adminportal',
            name='password',
            field=models.CharField(default='', max_length=50),
        ),
    ]
